import Head from 'next/head'
import { Box, Container, CssBaseline, Typography, Modal, Button, Grid } from '@mui/material'
import FavoriteBorderIcon from '@mui/icons-material/FavoriteBorder';
import CardGiftcardIcon from '@mui/icons-material/CardGiftcard';
import AccessibilityNewIcon from '@mui/icons-material/AccessibilityNew';
import Link from 'next/link';
import React from 'react'

const style = {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: 600,
    bgcolor: 'background.paper',
    boxShadow: 24,
    p: 4,
    borderRadius: 4,
};
export default function Home() {
    const [abiertoPoema, setAbierto] = React.useState(false);
    const [abiertoCorazon, setAbiertoCorazon] = React.useState(false);
    const abrirCorazon = () => setAbiertoCorazon(true);
    const cerrarCorazon = () => setAbiertoCorazon(false);
    const abrirPoema = () => setAbierto(true);
    const cerrar = () => setAbierto(false);
    return (
        <>
            <Head>
                <title>Día de las madres</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <main>
                {/* nav */}
                <nav>
                    <img src="flor.png" alt="" />
                    <Typography sx={{ color: 'white', my: 'auto', fontStyle: 'italic' }}>Día de las madres</Typography>
                    <img src="flor.png" alt="" />
                </nav>
                {/* contenido */}
                <Box sx={{ display: 'flex', backgroundColor: 'salmon', height: '100%', borderRadius: '5px', mx: 1 }}>
                    <Container sx={{ m: 1 }}>
                        <Box sx={{ borderRadius: '5px', mt: 2 }}>
                            <img src="mama.jpg" alt="" />
                        </Box>
                    </Container>

                    <Container sx={{ height: "100%", m: 1, alignContent: 'center', mt: 2 }}>
                        <Typography container='h1' variant='h3' color='white' sx={{ fontStyle: 'italic' }}>
                            Este es tu día, ¡Felicidades!
                        </Typography>
                        <Typography py={4} fontStyle='italic' color='whitesmoke'>
                            Elige un regalo:
                        </Typography>
                        <Grid container spacing={10}>
                            <Grid item xs={3}>
                                <Button onClick={abrirPoema} sx={{ "&:hover": { backgroundColor: 'indianred' }, height: '50px', width: '45px', backgroundColor: '#f37d7d', color: 'blanchedalmond' }} variant="contained">
                                    <FavoriteBorderIcon />
                                </Button>
                                <Modal
                                    open={abiertoPoema}
                                    onClose={cerrar}
                                    aria-labelledby="modal-modal-title"
                                    aria-describedby="modal-modal-description"
                                >
                                    <Box sx={style}>
                                        <Typography id="modal-modal-title" variant="h6" component="h2" textAlign='center'>
                                            Poema para mamá
                                        </Typography>
                                        <Typography id="modal-modal-description" sx={{ mt: 2, textShadow: 'none', fontStyle: 'italic', textAlign: 'center', wordSpacing: 3, p: 3 }}>
                                            Madre, tú eres la dulzura,
                                            tus manos son la ternura,
                                            que nos brinda protección.
                                            Es la sonrisa tu esencia,
                                            que marca la diferencia
                                            al entregarnos amor.

                                            Nos entibia tu mirada
                                            y la paciencia es tu aliada,
                                            esforzada en tu labor.
                                            ¡Tantas noches de desvelo!
                                            tanta lágrima y pañuelo
                                            ¡para darnos lo mejor!

                                            Tantas horas dedicadas
                                            con sonrisas dibujadas
                                            para hamacar mi soñar.
                                            Entre besos, entre abrazos
                                            fuiste creando los lazos
                                            porque tú eres ejemplar.
                                        </Typography>
                                        <Button onClick={cerrar} sx={{ "&:hover": { backgroundColor: 'indianred' }, height: '50px', width: '45px', backgroundColor: '#f37d7d', color: 'whitesmoke' }} variant="contained">
                                            Cerrar
                                        </Button>
                                    </Box>
                                </Modal>
                            </Grid>
                            <Grid item xs={3}>
                                <Button onClick={abrirCorazon} sx={{ "&:hover": { backgroundColor: 'indianred' }, height: '50px', width: '45px', backgroundColor: '#f37d7d', color: 'blanchedalmond' }} variant="contained">
                                    <AccessibilityNewIcon />
                                </Button>
                                <Modal
                                    open={abiertoCorazon}
                                    onClose={cerrarCorazon}
                                    aria-labelledby="modal-modal-title"
                                    aria-describedby="modal-modal-description"
                                >
                                    <Box sx={{ display: 'flex', py: 10 }}>
                                        <Grid container>
                                            <Grid item row xs={12} display={'flex'} sx={{ mx: 'auto' }}>
                                                <Container sx={{ display: 'flex', justifyContent: 'center' }}>
                                                    <div id='corazon'></div>
                                                    <div id='corazon'></div>
                                                    <div id='corazon'></div>
                                                    <div id='corazon'></div>
                                                    <div id='corazon'></div>
                                                    <div id='corazon'></div>
                                                    <div id='corazon'></div>
                                                    <div id='corazon'></div>
                                                </Container>

                                            </Grid>
                                            <Grid item row xs={12} display={'flex'}>
                                                <Container sx={{ display: 'flex', justifyContent: 'center' }}>

                                                    <div id='corazon'></div>
                                                    <div id='corazon'></div>
                                                    <div id='corazon'></div>
                                                    <div id='corazon'></div>
                                                    <div id='corazon'></div>
                                                    <div id='corazon'></div>
                                                    <div id='corazon'></div>
                                                    <div id='corazon'></div>
                                                </Container>

                                            </Grid>
                                            <Grid item row xs={12} display={'flex'}>
                                                <Container sx={{ display: 'flex', justifyContent: 'center' }}>

                                                    <div id='corazon'></div>
                                                    <div id='corazon'></div>
                                                    <div id='corazon'></div><div id='corazon'></div>
                                                    <div id='corazon'></div>
                                                    <div id='corazon'></div>
                                                    <div id='corazon'></div><div id='corazon'></div>
                                                </Container>
                                            </Grid>
                                            <Grid item row xs={12} display={'flex'}>
                                                <Container sx={{ display: 'flex', justifyContent: 'center' }}>

                                                    <div id='corazon'></div><div id='corazon'></div>
                                                    <div id='corazon'></div><div id='corazon'></div>
                                                    <div id='corazon'></div>
                                                    <div id='corazon'></div>
                                                    <div id='corazon'></div>
                                                    <div id='corazon'></div>
                                                </Container>

                                            </Grid>
                                        </Grid>
                                    </Box>
                                </Modal>
                            </Grid>
                            <Grid item xs={3}>
                                <Button sx={{ "&:hover": { backgroundColor: 'indianred' }, height: '50px', width: '45px', backgroundColor: '#f37d7d' }} variant="contained">
                                    <Link href="https://www.youtube.com/watch?v=krODzSXxx3A&pp=ygURZGlhIGRlIGxhcyBtYWRyZXM%3D" style={{ color: 'blanchedalmond' }} target='_blank'>
                                        <CardGiftcardIcon />
                                    </Link>
                                </Button>

                            </Grid>
                        </Grid>
                    </Container>
                </Box>
            </main>
        </>
    )
}
